import { BoardField } from "./BoardField";
import { Dispatcher } from "../Dispatcher";

export class Board extends Dispatcher {
    public fields: Map<string, BoardField>;
    private millCombos: Array<Array<string>>;
    public fieldGraphMatrix: any;
    public turn: number;


    constructor() {
        super();
        this.turn = -1;
        this.fields = new Map<string, BoardField>();
        var fieldlist = ['a7', 'd7', 'g7', 'b6', 'd6', 'f6', 'c5', 'd5', 'e5', 'a4', 'b4', 'c4', 'e4', 'f4', 'g4', 'c3', 'd3', 'e3', 'b2', 'd2', 'f2', 'a1', 'd1', 'g1'];
        for (var fieldname of fieldlist) {
            let field = new BoardField(fieldname);
            this.fields.set(fieldname, field);
            let dom = field.getDOM();
            field.setOwnership(-1);
            dom.onclick = () => this.onFieldClick(field);
            $(dom).html(fieldname.toUpperCase());
            //$(dom).on("click",  });
        }
        this.millCombos = [
            ['a7', 'd7', 'g7'],
            ['b6', 'd6', 'f6'],
            ['c5', 'd5', 'e5'],
            ['a4', 'b4', 'c4'],
            ['e4', 'f4', 'g4'],
            ['c3', 'd3', 'e3'],
            ['b2', 'd2', 'f2'],
            ['a1', 'd1', 'g1'], //end horizontals
            ['a7', 'a4', 'a1'],
            ['b6', 'b4', 'b2'],
            ['c5', 'c4', 'c3'],
            ['d7', 'd6', 'd5'],
            ['d3', 'd2', 'd1'],
            ['e5', 'e4', 'e3'],
            ['f6', 'f4', 'f2'],
            ['g7', 'g4', 'g1'], //end verticals
            ['a7', 'b6', 'c5'],
            ['e5', 'f6', 'g7'],
            ['e3', 'f2', 'g1'],
            ['a1', 'b2', 'c3'] //end diagonals
        ];
        this.fieldGraphMatrix = {
            "a7d7": true,
            "a7g7": false,
            "a7b6": true,
            "a7d6": false,
            "a7f6": false,
            "a7c5": false,
            "a7d5": false,
            "a7e5": false,
            "a4a7": true,
            "a7b4": false,
            "a7c4": false,
            "a7e4": false,
            "a7f4": false,
            "a7g4": false,
            "a7c3": false,
            "a7d3": false,
            "a7e3": false,
            "a7b2": false,
            "a7d2": false,
            "a7f2": false,
            "a1a7": false,
            "a7d1": false,
            "a7g1": false,
            "d7g7": true,
            "b6d7": false,
            "d6d7": true,
            "d7f6": false,
            "c5d7": false,
            "d5d7": false,
            "d7e5": false,
            "a4d7": false,
            "b4d7": false,
            "c4d7": false,
            "d7e4": false,
            "d7f4": false,
            "d7g4": false,
            "c3d7": false,
            "d3d7": false,
            "d7e3": false,
            "b2d7": false,
            "d2d7": false,
            "d7f2": false,
            "a1d7": false,
            "d1d7": false,
            "d7g1": false,
            "b6g7": false,
            "d6g7": false,
            "f6g7": true,
            "c5g7": false,
            "d5g7": false,
            "e5g7": false,
            "a4g7": false,
            "b4g7": false,
            "c4g7": false,
            "e4g7": false,
            "f4g7": false,
            "g4g7": true,
            "c3g7": false,
            "d3g7": false,
            "e3g7": false,
            "b2g7": false,
            "d2g7": false,
            "f2g7": false,
            "a1g7": false,
            "d1g7": false,
            "g1g7": false,
            "b6d6": true,
            "b6f6": false,
            "b6c5": true,
            "b6d5": false,
            "b6e5": false,
            "a4b6": false,
            "b4b6": true,
            "b6c4": false,
            "b6e4": false,
            "b6f4": false,
            "b6g4": false,
            "b6c3": false,
            "b6d3": false,
            "b6e3": false,
            "b2b6": false,
            "b6d2": false,
            "b6f2": false,
            "a1b6": false,
            "b6d1": false,
            "b6g1": false,
            "d6f6": true,
            "c5d6": false,
            "d5d6": true,
            "d6e5": false,
            "a4d6": false,
            "b4d6": false,
            "c4d6": false,
            "d6e4": false,
            "d6f4": false,
            "d6g4": false,
            "c3d6": false,
            "d3d6": false,
            "d6e3": false,
            "b2d6": false,
            "d2d6": false,
            "d6f2": false,
            "a1d6": false,
            "d1d6": false,
            "d6g1": false,
            "c5f6": false,
            "d5f6": false,
            "e5f6": true,
            "a4f6": false,
            "b4f6": false,
            "c4f6": false,
            "e4f6": false,
            "f4f6": true,
            "f6g4": false,
            "c3f6": false,
            "d3f6": false,
            "e3f6": false,
            "b2f6": false,
            "d2f6": false,
            "f2f6": false,
            "a1f6": false,
            "d1f6": false,
            "f6g1": false,
            "c5d5": true,
            "c5e5": false,
            "a4c5": false,
            "b4c5": false,
            "c4c5": true,
            "c5e4": false,
            "c5f4": false,
            "c5g4": false,
            "c3c5": false,
            "c5d3": false,
            "c5e3": false,
            "b2c5": false,
            "c5d2": false,
            "c5f2": false,
            "a1c5": false,
            "c5d1": false,
            "c5g1": false,
            "d5e5": true,
            "a4d5": false,
            "b4d5": false,
            "c4d5": false,
            "d5e4": false,
            "d5f4": false,
            "d5g4": false,
            "c3d5": false,
            "d3d5": false,
            "d5e3": false,
            "b2d5": false,
            "d2d5": false,
            "d5f2": false,
            "a1d5": false,
            "d1d5": false,
            "d5g1": false,
            "a4e5": false,
            "b4e5": false,
            "c4e5": false,
            "e4e5": true,
            "e5f4": false,
            "e5g4": false,
            "c3e5": false,
            "d3e5": false,
            "e3e5": false,
            "b2e5": false,
            "d2e5": false,
            "e5f2": false,
            "a1e5": false,
            "d1e5": false,
            "e5g1": false,
            "a4b4": true,
            "a4c4": false,
            "a4e4": false,
            "a4f4": false,
            "a4g4": false,
            "a4c3": false,
            "a4d3": false,
            "a4e3": false,
            "a4b2": false,
            "a4d2": false,
            "a4f2": false,
            "a1a4": true,
            "a4d1": false,
            "a4g1": false,
            "b4c4": true,
            "b4e4": false,
            "b4f4": false,
            "b4g4": false,
            "b4c3": false,
            "b4d3": false,
            "b4e3": false,
            "b2b4": true,
            "b4d2": false,
            "b4f2": false,
            "a1b4": false,
            "b4d1": false,
            "b4g1": false,
            "c4e4": false,
            "c4f4": false,
            "c4g4": false,
            "c3c4": true,
            "c4d3": false,
            "c4e3": false,
            "b2c4": false,
            "c4d2": false,
            "c4f2": false,
            "a1c4": false,
            "c4d1": false,
            "c4g1": false,
            "e4f4": true,
            "e4g4": false,
            "c3e4": false,
            "d3e4": false,
            "e3e4": true,
            "b2e4": false,
            "d2e4": false,
            "e4f2": false,
            "a1e4": false,
            "d1e4": false,
            "e4g1": false,
            "f4g4": true,
            "c3f4": false,
            "d3f4": false,
            "e3f4": false,
            "b2f4": false,
            "d2f4": false,
            "f2f4": true,
            "a1f4": false,
            "d1f4": false,
            "f4g1": false,
            "c3g4": false,
            "d3g4": false,
            "e3g4": false,
            "b2g4": false,
            "d2g4": false,
            "f2g4": false,
            "a1g4": false,
            "d1g4": false,
            "g1g4": true,
            "c3d3": true,
            "c3e3": false,
            "b2c3": true,
            "c3d2": false,
            "c3f2": false,
            "a1c3": false,
            "c3d1": false,
            "c3g1": false,
            "d3e3": true,
            "b2d3": false,
            "d2d3": true,
            "d3f2": false,
            "a1d3": false,
            "d1d3": false,
            "d3g1": false,
            "b2e3": false,
            "d2e3": false,
            "e3f2": true,
            "a1e3": false,
            "d1e3": false,
            "e3g1": false,
            "b2d2": true,
            "b2f2": false,
            "a1b2": true,
            "b2d1": false,
            "b2g1": false,
            "d2f2": true,
            "a1d2": false,
            "d1d2": true,
            "d2g1": false,
            "a1f2": false,
            "d1f2": false,
            "f2g1": true,
            "a1d1": true,
            "a1g1": false,
            "d1g1": true
        };
    }
    public isMill(field: BoardField) {
        if (field.value == -1) return false;
        for (var millCombo of this.millCombos) {
            if (millCombo.includes(field.name)) {
                var comboMet = true;
                for (var potentialMillFieldName of millCombo) {
                    var potentialMillField = this.fields.get(potentialMillFieldName);
                    if (field.value != potentialMillField.value) {
                        comboMet = false;
                        break;
                    }
                }
                if (comboMet) return true;
            }
        }
        return false;
    }
    public isDraw() {
        for (var field of this.fields.values()) {
            if (field.value != -1) return false;
        }
        return true;
    }
    public onFieldClick(field: BoardField) {
        console.log("clicked on field " + field.name);
        this.dispatchEvent("field_click", field);
    }
}